//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cource_Wall_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Info { get; set; }
        public string FileName { get; set; }
        public byte[] File { get; set; }
        public string Comment { get; set; }
        public int Position { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
    
        public virtual Positions Positions { get; set; }
    }
}
